Setup
melaniesigrid/Leaderboard pull request #1
Opened 2022-01-26 17:00 UTC by melaniesigrid

Thank you for reviewing my project! On this PR...
- Create setup and basic skeleton for Leaderboard project using GitFlow and Webpack.

<img src="https://media3.giphy.com/media/2tTiCSfEEP5QS5TjGr/giphy.gif"/>

2022-01-26 17:28 UTC, rloterh requested changes
Hi Melanie, 

You did extremely great on this project! 👏 👏 
There are however a few issues that you still need to work on to go to the next project but you are almost there! 🚦  🚦  

## Good Points 👍  
- No linter errors


## Required Changes ♻️
_Kindly check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

_Kindly check the comments marked **[OPTIONAL]** under the review._
<br>
Cheers and Happy coding!👏 💻 🍷

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-26 17:28 UTC, rloterh commented on README.md
> +## Authors
- [ ] OPTIONAL:
Kindly change the header title _Authors_ to _Author_, as this project is done solely. This will make your ReadMe appear more professional.

2022-01-26 17:28 UTC, rloterh commented on .gitignore
> +node_modules/
- [ ] The _node_modules_ directory is improperly excluded from the list, hence this directly is showing in the project structure. Kindly ensure to fix this issue by clearing your Github cache.

**Your project structure:**
![image](https://user-images.githubusercontent.com/12745474/151214871-3acfeb45-05b3-4d5a-a306-997a3305ce69.png)

2022-01-26 19:21 UTC, melaniesigrid commented on README.md
> +## Authors
Thank you for your comment! I have taken care of this point.

2022-01-26 19:22 UTC, melaniesigrid commented on .gitignore
> +node_modules/
Thank you for teaching me a new technique! I have learned and removed the cache.

2022-01-28 06:20 UTC, rloterh commented on .gitignore
> +node_modules/
My pleasure...Happy coding! 💻 🍷 ☺️

2022-01-28 06:20 UTC, rloterh commented on README.md
> +## Authors
My pleasure...Happy coding! 💻 🍷 ☺️

2022-01-29 01:27 UTC, closed without merging